
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('99add560-c924-449c-affd-5b72282448be',1, 1, 'Especialidad', 'Civil',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('d22c3f74-659e-4614-8ebe-39f05834a899',1, 2, 'Especialidad', 'Laboral',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('bdcd19b8-f0e6-42a8-8c30-0a374e3e93fd',1, 3, 'Especialidad', 'Penal',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('cefa8fb6-50d3-4223-92b2-579b90384784',2, 1, 'DerechoFundamental', 'Vida',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('859486ef-b37d-4b9b-b004-2c0677448ab3',2, 2, 'DerechoFundamental', 'Libertad',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('5e2d614c-e9df-4286-ab80-6b32b2455286',3, 1, 'EstadoExpediente', 'SinAsignar',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('0a7f69ff-800a-4f14-9e05-644aa6c3ce0a',3, 2, 'EstadoExpediente', 'Asignado',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('a6ce0c32-5880-4bb9-8363-1af3e1ae10c5',3, 3, 'EstadoExpediente', 'Resuelto',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('deadc8d5-5a98-4b18-86fd-c616672da9a0',3, 4, 'EstadoExpediente', 'Cerrado',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('92820e58-1ed2-47dc-8efd-282b89e7d0e5',3, 5, 'EstadoExpediente', 'Devuelto',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('3faa3de9-55c5-4bda-8eb0-054a7e6fe394',4, 1, 'TipoArchivo', 'CargadoCiudadano',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('fcc2fe3e-afaa-48a5-9fb3-840cfcd932db',4, 2, 'TipoArchivo', 'RespuestaExpediente',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('bc16640c-62cd-42cd-b301-704d162e76ba',5, 1, 'TipoDocumento', 'Nit',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('b075f9ca-256a-4b9d-baaf-8d5307cb0619',5, 2, 'TipoDocumento', 'CC',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);
INSERT INTO "Parametro" (id, "IdCategoria", "IdParametro", "DetalleCategoria", "DetalleParametro", "Estado",   "fechaCreacion","UsuarioCrea", "fechaEdicion","usuarioModifica", "fechaEliminacion", "UsuarioElimina")VALUES('d6bfff38-854c-41b7-a781-d7cf05d8d491',5, 3, 'TipoDocumento', 'CE',1, current_timestamp, 'SISTEMA', current_timestamp,'' , NULL, NULL);


SELECT * FROM "Parametro" 
--where "IdCategoria"=2


