
version: '3.7'

services:

  expedientedigservice-prod:
    container_name: expedientedigservice-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8088:80'
    volumes:      
      - uploadVolume:/var/Uploads
volumes:
  uploadVolume: {}

#docker-compose -f docker-compose.yml up --build -d
